[tool.poetry]
name = "arxiv-browse"
version = "0.3.2.6"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
python-dateutil = "*"
Flask-API = "*"
Flask-SQLAlchemy = "==2.4.4"  
MarkupSafe = "*"
SQLAlchemy = "==1.3.20" 
pytz = "*"
mysqlclient = "==1.4.1"
mmh3 = "*"
aiohttp = "==3.6.2"
flask = "1.1.4"  
validators = "*"
mypy-extensions = "*"
flask-wtf = "*"
arxiv-auth = "==0.4.2rc1"
mypy = "*"
flask-s3 = "*"
arxiv-base = "==0.17.2.1"
retry = "==0.9.2"
geoip2 = "*"
bcrypt = "*"
pydantic = "*"

[tool.poetry.dev-dependencies]
pylama = "*"
nose2 = "*"
sqlacodegen = "*"
Flask-Testing = "*"
pycodestyle = "*"
pydocstyle = "*"
pylint = "*"
pytest = "*"
pytest-html = "*"
ansi2html = "*"
hypothesis = "*"
beautifulsoup4 = "*"
pyhamcrest = "*"
pytest-easyread = "*"
weighted-levenshtein = "*"
coverage = "*"
coveralls = "*"
sphinx = "*"
sphinx-autodoc-typehints = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
